### ISSUE TITLE
Web mode is not activated if multiple <template> tags are present

### ISSUE THREAD

**Issue by jethrokuan** [CodeFalling/vue-mode#2]
I have a template that looks like this:

```
<template>
    <template v-if="loading">
      <foo></foo>
    </template>
    <template v-else>  
       <bar></bar>
    </template>
</template>
```

web mode is not activated for the whole template, but only for:

```
<template>
    <template v-if="loading">
      <foo></foo>
    </template>
```

**Comment by geekx63** [comment]
I also encountered the same problem

**Comment by natecox** [comment]
I can also confirm this.

[![asciicast](https://asciinema.org/a/cznoanjo371m40v1782qiikzz.png)](https://asciinema.org/a/cznoanjo371m40v1782qiikzz)

**Comment by AdamNiederer** [comment]
The current method of partitioning the buffer relies on regular expressions, which obviously have an issue balancing the template tags. It may be wise to either narrow the html portion of the buffer before looking for the tags, or using a more complex mechanism for activating mmm-mode.

I'll take a look at this soon-ish, because I'm running into the same issue.
